server {
    listen 3000;
    server_tokens off;
    server_name app;
    root /code/build/;
    
    location /sockets {
        root   /code/build;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}