server {
    listen 80;
    server_tokens off;
    root /code/build/;
    
    location / {
        root   /code/build;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}