server {
    server_tokens off;
    listen 3000;
    root /code/build/;
    
    location / {
        root   /code/build;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}