# server {
#     listen 8000;
#     server_tokens off;

#     location / {
#         proxy_pass http://backend:8000;
#     }

#     location /sockets {
#         proxy_pass http://backend:8000/sockets;
#     }
# }
server {
    listen 8000;
    server_tokens off;
    # server_name backend;

    location / {
        proxy_pass http://172.20.0.3:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /sockets {
        proxy_pass http://172.20.0.3:8000/sockets;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}